import fs from 'node:fs';
import path from 'node:path';

// Adapt existing color utilities without changing fixed brand buttons or dark banners.
const root = path.resolve(import.meta.dirname, '../src');
const files = fs.readdirSync(root, { recursive: true }).filter(f => /\.(jsx|js)$/.test(f));
const groups = new Map();
for (const file of files) {
  const source = fs.readFileSync(path.join(root, file), 'utf8');
  for (const match of source.matchAll(/(?:(?:hover|focus|focus-visible|group-hover|placeholder):)?(?:bg|text|border|divide|from|via|to)-(?:white|(?:slate|gray|teal|emerald|green|orange|amber|yellow|red|rose|blue|indigo|purple|violet|cyan|sky)-\d{2,3}|\[#[0-9a-fA-F]{6}\])(?:\/\d+)?/g)) {
    const token = match[0];
    const [variant, utility] = token.includes(':') ? token.split(':') : ['', token];
    const [, kind, color, opacity] = utility.match(/^(bg|text|border|divide|from|via|to)-(.+?)(?:\/(\d+))?$/);
    const neutral = /^(white|(?:slate|gray)-(50|100|200)|\[#(?:FFFFFF|F8FAF8|F8FAF9|F8FAFC)\])$/i.test(color);
    const shade = Number(color.match(/-(\d+)$/)?.[1]);
    let value;
    let property;
    if (['bg', 'from', 'via', 'to'].includes(kind)) {
      if (neutral) value = color === 'white' || /FFFFFF/i.test(color) ? 'var(--theme-surface)' : 'var(--theme-subtle)';
      else if (shade <= 100) value = 'var(--theme-tint)';
      property = kind === 'bg' ? 'background-color' : `--tw-gradient-${kind}`;
    } else if (kind === 'text') {
      if (/^(slate|gray)-(700|800|900|950)$/.test(color) || /\[#0F172A\]/i.test(color)) value = 'var(--theme-text)';
      else if (/^(slate|gray)-(500|600)$/.test(color)) value = 'var(--theme-muted)';
      else if (/\[#(?:005F60|004D4E|004D40|004041)\]/i.test(color)) value = '#5eead4';
      else if (/\[#(?:E06D14|C2580E)\]/i.test(color)) value = '#fdba74';
      else if (shade >= 600 && !/^(slate|gray)-/.test(color)) value = { teal: '#5eead4', emerald: '#6ee7b7', green: '#86efac', orange: '#fdba74', amber: '#fcd34d', yellow: '#fde047', red: '#fca5a5', rose: '#fda4af', blue: '#93c5fd', indigo: '#a5b4fc', purple: '#d8b4fe', violet: '#c4b5fd', cyan: '#67e8f9', sky: '#7dd3fc' }[color.split('-')[0]];
      property = 'color';
    } else {
      if (neutral || shade <= 300) value = 'var(--theme-border)';
      property = 'border-color';
    }
    if (!value) continue;
    if (opacity) value = `color-mix(in srgb, ${value} ${opacity}%, transparent)`;
    let selector = '.' + token.replace(/[^a-zA-Z0-9_-]/g, c => '\\' + c);
    if (variant === 'group-hover') selector = `.group:hover ${selector}`;
    else if (variant === 'placeholder') selector += '::placeholder';
    else if (variant) selector += ':' + variant;
    if (kind === 'divide') selector += ' > :not(:last-child)';
    const declaration = `${property}: ${value};`;
    if (!groups.has(declaration)) groups.set(declaration, new Set());
    groups.get(declaration).add(selector);
  }
}
let css = `/* Generated by scripts/generate-theme.mjs. Run after adding legacy color utilities.
   New components should use the semantic --theme-* tokens directly. */
:root {
  color-scheme: light;
  --theme-surface: #ffffff;
  --theme-subtle: #f8fafc;
  --theme-text: #0f172a;
  --theme-muted: #475569;
  --theme-border: #e2e8f0;
}
:root[data-theme="dark"] {
  color-scheme: dark;
  --theme-surface: #172334;
  --theme-subtle: #101a29;
  --theme-text: #e5edf5;
  --theme-muted: #a8b8cc;
  --theme-border: #35465b;
  --theme-tint: #193338;
  --udaan-slate-900: #e5edf5;
  --udaan-slate-600: #a8b8cc;
  --udaan-slate-50: #101a29;
}
body { background-color: var(--theme-subtle); color: var(--theme-text); }
.theme-toggle {
  background: var(--theme-surface);
  color: var(--theme-text);
  border-color: var(--theme-border);
}
.theme-toggle:hover { background: var(--theme-subtle); }
`;
for (const [declaration, selectors] of groups) {
  css += '\n' + [...selectors].sort().map(s => `:root[data-theme="dark"] ${s}`).join(',\n') + ` { ${declaration} }\n`;
}
fs.writeFileSync(path.join(root, 'styles/theme.css'), css);
