"""
Karnataka Education & Career Pathway Seed Dataset
Provides realistic post-SSLC (Class 10) and post-PUC pathways with options & milestone steps.
"""

INITIAL_PATHWAYS_DATA = [
    {
        "id": "c10-puc",
        "education_level": "Class 10",
        "stream": None,
        "title": "Pre-University College (PUC)",
        "category": "Pre-University",
        "duration": "2 Years",
        "description": "Two-year Pre-University course under the Department of Pre-University Education, Karnataka. Main academic route after SSLC leading to degree programs in Engineering, Medicine, Commerce, Law, and Arts.",
        "options": [
            {
                "option_name": "Science Stream (PCMB / PCMC / PCME)",
                "stream_or_code": "PCMB / PCMC",
                "description": "Physics, Chemistry, Mathematics with Biology, Computer Science, or Electronics. Prepares students for KCET, NEET, JEE, and pure science degrees.",
                "eligibility": "Class 10 SSLC / CBSE / ICSE Pass",
                "display_order": 1,
            },
            {
                "option_name": "Commerce Stream (CEBA / SEBA / HEBA)",
                "stream_or_code": "CEBA / SEBA",
                "description": "Computer Science, Economics, Business Studies, and Accountancy. Foundation for CA, CS, B.Com, BBA, and finance careers.",
                "eligibility": "Class 10 SSLC / CBSE / ICSE Pass",
                "display_order": 2,
            },
            {
                "option_name": "Arts / Humanities Stream (HEPS / EGAS)",
                "stream_or_code": "HEPS / EGAS",
                "description": "History, Economics, Political Science, Sociology / Psychology. Foundation for Law, Civil Services (KPSC/UPSC), Journalism, and Social Sciences.",
                "eligibility": "Class 10 SSLC / CBSE / ICSE Pass",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "SSLC Board Completion",
                "description": "Score qualifying marks in SSLC / Class 10 board examinations.",
                "key_action": "Obtain official SSLC Marks Card",
            },
            {
                "step_number": 2,
                "title": "Stream Selection & Counseling",
                "description": "Choose Science, Commerce, or Arts based on aptitude and long-term career goals.",
                "key_action": "Apply via SATS / PU Department Admission Portal",
            },
            {
                "step_number": 3,
                "title": "PUC Coursework & Entrance Prep",
                "description": "Complete 1st and 2nd PUC syllabus while preparing for targeted competitive entrance exams.",
                "key_action": "Prepare for KCET / NEET / CA Foundation",
            },
        ],
    },
    {
        "id": "c10-diploma",
        "education_level": "Class 10",
        "stream": None,
        "title": "Polytechnic Diploma Engineering",
        "category": "Technical",
        "duration": "3 Years",
        "description": "3-year practical technical engineering diploma under Directorate of Technical Education (DTE), Karnataka. Enables direct 2nd-year B.E / B.Tech lateral entry via DCET.",
        "options": [
            {
                "option_name": "Computer Science & Engineering Diploma",
                "stream_or_code": "CS-DIP",
                "description": "Software programming, web development, computer networking, hardware troubleshooting, and database basics.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 1,
            },
            {
                "option_name": "Mechanical & Civil Engineering Diploma",
                "stream_or_code": "ME-CE-DIP",
                "description": "Engineering drawing, CAD software, building construction, manufacturing technology, and mechanics.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 2,
            },
            {
                "option_name": "Electronics & Communication Diploma",
                "stream_or_code": "EC-DIP",
                "description": "Embedded systems, microcontrollers, IoT devices, electronic circuits, and digital communications.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "DTE Polytechnic Seat Allotment",
                "description": "Participate in DTE Karnataka merit-based polytechnic admission rounds.",
                "key_action": "Register on DTE Karnataka Admission Portal",
            },
            {
                "step_number": 2,
                "title": "3-Year Lab & Workshop Training",
                "description": "Complete hands-on engineering lab modules, industrial visits, and semester exams.",
                "key_action": "Maintain >60% aggregate score for B.E eligibility",
            },
            {
                "step_number": 3,
                "title": "DCET Lateral Entry or Industry Job",
                "description": "Take Diploma CET for lateral entry into 2nd year B.E/B.Tech or join industry as Diploma Engineer.",
                "key_action": "Take DCET Exam or Attend Campus Placement",
            },
        ],
    },
    {
        "id": "c10-iti",
        "education_level": "Class 10",
        "stream": None,
        "title": "Industrial Training Institute (ITI) Trade",
        "category": "Vocational",
        "duration": "1 - 2 Years",
        "description": "Skill-focused vocational trade certificates under Department of Employment and Training (DET), Karnataka and NCVT/SCVT.",
        "options": [
            {
                "option_name": "Electrician Trade",
                "stream_or_code": "ITI-ELEC",
                "description": "Industrial & domestic electrical wiring, motor maintenance, transformer operations, and electrical safety.",
                "eligibility": "Class 10 Pass",
                "display_order": 1,
            },
            {
                "option_name": "Fitter / Turner Trade",
                "stream_or_code": "ITI-FIT",
                "description": "Precision metal machining, lathe operation, bench fitting, blueprint reading, and mechanical maintenance.",
                "eligibility": "Class 10 Pass",
                "display_order": 2,
            },
            {
                "option_name": "COPA (Computer Operator & Programming Assistant)",
                "stream_or_code": "ITI-COPA",
                "description": "Computer fundamentals, OS installation, office automation packages, database management, and basic web design.",
                "eligibility": "Class 10 Pass",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "DET Karnataka ITI Admissions",
                "description": "Apply for NCVT/SCVT trade seats in government or private ITIs in Karnataka.",
                "key_action": "Submit Online ITI Counseling Form",
            },
            {
                "step_number": 2,
                "title": "Practical Workshop Apprenticeship",
                "description": "Complete intensive practical shop-floor training and National Trade Certificate (NTC) exams.",
                "key_action": "Pass NCVT All India Trade Test (AITT)",
            },
            {
                "step_number": 3,
                "title": "Industry Employment / Self-Employment",
                "description": "Join public sector utilities (KPTCL, BESCOM), manufacturing plants, or set up an independent technical workshop.",
                "key_action": "Register on NATS Apprenticeship Portal",
            },
        ],
    },
    {
        "id": "puc-science-eng",
        "education_level": "PUC 2",
        "stream": "Science",
        "title": "Engineering & Technology Degrees (B.E / B.Tech)",
        "category": "Higher Education",
        "duration": "4 Years",
        "description": "4-year professional undergraduate engineering degree programs under Visvesvaraya Technological University (VTU) and autonomous engineering colleges in Karnataka.",
        "options": [
            {
                "option_name": "Computer Science / AI & ML Engineering",
                "stream_or_code": "B.E CS/AI",
                "description": "Software architecture, artificial intelligence, cloud computing, algorithms, and web systems.",
                "eligibility": "PUC 2 Science with Physics & Math (Min 45% aggregate)",
                "display_order": 1,
            },
            {
                "option_name": "Electronics & Communication Engineering",
                "stream_or_code": "B.E ECE",
                "description": "Semiconductors, VLSI chip design, embedded systems, robotics, and signal processing.",
                "eligibility": "PUC 2 Science with Physics & Math (Min 45% aggregate)",
                "display_order": 2,
            },
            {
                "option_name": "Mechanical & Civil Engineering",
                "stream_or_code": "B.E ME/CV",
                "description": "CAD/CAM manufacturing, robotics, structural design, transportation, and green building technologies.",
                "eligibility": "PUC 2 Science with Physics & Math (Min 45% aggregate)",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "KCET / JEE Main Entrance Exam",
                "description": "Appear for Karnataka CET or JEE Main for government and private engineering seat allocation.",
                "key_action": "Register for KEA Engineering Counseling",
            },
            {
                "step_number": 2,
                "title": "VTU Academic Coursework & Projects",
                "description": "Complete 8 semesters of core subjects, practical laboratories, and team mini-projects.",
                "key_action": "Maintain CGPA >7.5",
            },
            {
                "step_number": 3,
                "title": "Industry Internship & Campus Placements",
                "description": "Complete final-year capstone project and participate in IT/Engineering recruitment drives.",
                "key_action": "Build GitHub / Project Portfolio",
            },
        ],
    },
    {
        "id": "puc-commerce-fin",
        "education_level": "PUC 2",
        "stream": "Commerce",
        "title": "Commerce, Accounting & Business Management",
        "category": "Higher Education",
        "duration": "3 - 4 Years",
        "description": "Degree programs and professional certifications in finance, accounting, taxation, auditing, and corporate management.",
        "options": [
            {
                "option_name": "B.Com / B.Com (Honours in Finance)",
                "stream_or_code": "B.Com",
                "description": "Financial accounting, corporate taxation, auditing, banking, and business law.",
                "eligibility": "PUC 2 Commerce Pass",
                "display_order": 1,
            },
            {
                "option_name": "Chartered Accountancy (CA) / CS",
                "stream_or_code": "ICAI-CA",
                "description": "Premier professional qualification by ICAI covering statutory audit, tax advisory, and corporate governance.",
                "eligibility": "Pass CA Foundation Exam after PUC 2",
                "display_order": 2,
            },
            {
                "option_name": "BBA (Bachelor of Business Administration)",
                "stream_or_code": "BBA",
                "description": "Business leadership, digital marketing, human resources, corporate strategy, and startup management.",
                "eligibility": "PUC 2 Pass in any stream (Commerce preferred)",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "PUC 2 Board & Entrance Exams",
                "description": "Clear 2nd PUC exams and register for degree admissions or CA Foundation entrance.",
                "key_action": "Apply on Karnataka University Admission Portal",
            },
            {
                "step_number": 2,
                "title": "Undergraduate Study & Articleship",
                "description": "Complete degree coursework or CA Intermediate exams alongside 2 years of practical articleship training.",
                "key_action": "Obtain Tally / Advanced Excel Certification",
            },
            {
                "step_number": 3,
                "title": "CA Final / M.Com / Corporate Placement",
                "description": "Clear final professional exams or join financial institutions, audit firms, and multinational corporations.",
                "key_action": "Apply for Financial Analyst & Audit Roles",
            },
        ],
    },
    {
        "id": "puc-arts-hum",
        "education_level": "PUC 2",
        "stream": "Arts",
        "title": "Humanities, Law, Media & Civil Services",
        "category": "Higher Education",
        "duration": "3 - 5 Years",
        "description": "Degree pathways in legal studies, journalism, public policy, social sciences, and competitive civil service careers (KPSC / UPSC).",
        "options": [
            {
                "option_name": "Integrated BA LL.B (5-Year Law Degree)",
                "stream_or_code": "BA-LLB",
                "description": "Professional 5-year integrated law degree offered by National Law School (NLSIU Bengaluru) and KSLU affiliated colleges.",
                "eligibility": "PUC 2 Pass with Min 45% aggregate",
                "display_order": 1,
            },
            {
                "option_name": "BA Journalism & Mass Communication",
                "stream_or_code": "BA-JMC",
                "description": "Print & digital journalism, broadcasting, public relations, content creation, and media production.",
                "eligibility": "PUC 2 Pass",
                "display_order": 2,
            },
            {
                "option_name": "BA Economics & Political Science (Civil Services Track)",
                "stream_or_code": "BA-CIVIL",
                "description": "Undergraduate curriculum aligned with KPSC (KAS) and UPSC (IAS / IPS) general studies syllabi.",
                "eligibility": "PUC 2 Pass in Arts / Humanities",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "CLAT / University Entrance Exam",
                "description": "Appear for Common Law Admission Test (CLAT) or university entrance for BA degree programs.",
                "key_action": "Take CLAT / CUET Entrance Exam",
            },
            {
                "step_number": 2,
                "title": "Degree Study & Practical Internships",
                "description": "Participate in moot court competitions, media house internships, or district administration research projects.",
                "key_action": "Complete Legal / Media Internship",
            },
            {
                "step_number": 3,
                "title": "State Bar Council Enrollment / KPSC Exam",
                "description": "Enroll in Karnataka State Bar Council for legal practice or sit for KPSC KAS Civil Services Preliminary exam.",
                "key_action": "Register with Bar Council or KPSC Portal",
            },
        ],
    },
]
