"""
Karnataka Education & Career Pathway Seed Dataset
Provides realistic post-SSLC (Class 10) and post-PUC pathways with options & milestone steps.
"""

INITIAL_PATHWAYS_DATA = [
    # -------------------------------------------------------------
    # LEVEL 0: ROOTS (Class 10 / SSLC)
    # -------------------------------------------------------------
    {
        "id": "c10-puc",
        "recommendation_dimensions": ['science', 'commerce', 'arts'],
        "education_level": "Class 10",
        "stream": None,
        "title": "Pre-University College (PUC)",
        "category": "Pre-University",
        "duration": "2 Years",
        "description": "Two-year Pre-University course under the Department of Pre-University Education, Karnataka. Main academic route after SSLC leading to degree programs in Engineering, Medicine, Commerce, Law, and Arts.",
        "parent_id": None,
        "options": [
            {
                "option_name": "Science Stream (PCMB / PCMC / PCME)",
                "stream_or_code": "Science",
                "description": "Physics, Chemistry, Mathematics with Biology, Computer Science, or Electronics. Prepares students for KCET, NEET, JEE, and pure science degrees.",
                "eligibility": "Class 10 SSLC / CBSE / ICSE Pass",
                "display_order": 1,
            },
            {
                "option_name": "Commerce Stream (CEBA / SEBA)",
                "stream_or_code": "Commerce",
                "description": "Computer Science, Economics, Business Studies, and Accountancy. Foundation for CA, CS, B.Com, BBA, and finance careers.",
                "eligibility": "Class 10 SSLC / CBSE / ICSE Pass",
                "display_order": 2,
            },
            {
                "option_name": "Arts / Humanities Stream (HEPS / EGAS)",
                "stream_or_code": "Arts",
                "description": "History, Economics, Political Science, Sociology / Psychology. Foundation for Law, Civil Services (KPSC/UPSC), Journalism, and Social Sciences.",
                "eligibility": "Class 10 SSLC / CBSE / ICSE Pass",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "SSLC Board Completion",
                "description": "Score qualifying marks in SSLC / Class 10 board examinations.",
                "key_action": "Obtain official SSLC Marks Card",
            },
            {
                "step_number": 2,
                "title": "Stream Selection & Counseling",
                "description": "Choose Science, Commerce, or Arts based on aptitude and long-term career goals.",
                "key_action": "Apply via SATS / PU Department Admission Portal",
            },
            {
                "step_number": 3,
                "title": "PUC Coursework & Entrance Prep",
                "description": "Complete 1st and 2nd PUC syllabus while preparing for targeted competitive entrance exams.",
                "key_action": "Prepare for KCET / NEET / CA Foundation",
            },
        ],
    },
    {
        "id": "c10-diploma",
        "recommendation_dimensions": ['diploma'],
        "education_level": "Class 10",
        "stream": None,
        "title": "Polytechnic Diploma",
        "category": "Technical",
        "duration": "3 Years",
        "description": "3-year practical technical engineering diploma under Directorate of Technical Education (DTE), Karnataka. Enables direct 2nd-year B.E / B.Tech lateral entry via DCET.",
        "parent_id": None,
        "options": [
            {
                "option_name": "Computer Science & Engineering Diploma",
                "stream_or_code": "CS-DIP",
                "description": "Software programming, web development, computer networking, hardware troubleshooting, and database basics.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 1,
            },
            {
                "option_name": "Electronics & Communication Diploma",
                "stream_or_code": "EC-DIP",
                "description": "Embedded systems, microcontrollers, IoT devices, electronic circuits, and digital communications.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 2,
            },
            {
                "option_name": "Mechanical Engineering Diploma",
                "stream_or_code": "ME-DIP",
                "description": "CAD/CAM manufacturing, robotics, automotive design, thermodynamics, and manufacturing processes.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 3,
            },
            {
                "option_name": "Civil Engineering Diploma",
                "stream_or_code": "CE-DIP",
                "description": "Surveying, building materials, structural design, construction management, and environmental systems.",
                "eligibility": "Class 10 Pass with Min 35% in Mathematics & Science",
                "display_order": 4,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "DTE Polytechnic Seat Allotment",
                "description": "Participate in DTE Karnataka merit-based polytechnic admission rounds.",
                "key_action": "Register on DTE Karnataka Admission Portal",
            },
            {
                "step_number": 2,
                "title": "3-Year Lab & Workshop Training",
                "description": "Complete hands-on engineering lab modules, industrial visits, and semester exams.",
                "key_action": "Maintain >60% aggregate score for B.E eligibility",
            },
            {
                "step_number": 3,
                "title": "DCET Lateral Entry or Industry Job",
                "description": "Take Diploma CET for lateral entry into 2nd year B.E/B.Tech or join industry as Diploma Engineer.",
                "key_action": "Take DCET Exam or Attend Campus Placement",
            },
        ],
    },
    {
        "id": "c10-iti",
        "recommendation_dimensions": ['iti'],
        "education_level": "Class 10",
        "stream": None,
        "title": "ITI Vocational Trades",
        "category": "Vocational",
        "duration": "1 - 2 Years",
        "description": "Skill-focused vocational trade certificates under Department of Employment and Training (DET), Karnataka and NCVT/SCVT.",
        "parent_id": None,
        "options": [
            {
                "option_name": "Electrician Trade",
                "stream_or_code": "ITI-ELEC",
                "description": "Industrial & domestic electrical wiring, motor maintenance, solar installations, and electrical safety.",
                "eligibility": "Class 10 Pass",
                "display_order": 1,
            },
            {
                "option_name": "Fitter / Turner Trade",
                "stream_or_code": "ITI-FIT",
                "description": "Precision metal machining, lathe operation, bench fitting, blueprint reading, and mechanical maintenance.",
                "eligibility": "Class 10 Pass",
                "display_order": 2,
            },
            {
                "option_name": "COPA (Computer Operator & Programming Assistant)",
                "stream_or_code": "ITI-COPA",
                "description": "Computer fundamentals, OS installation, office automation packages, database management, and basic web design.",
                "eligibility": "Class 10 Pass",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "DET Karnataka ITI Admissions",
                "description": "Apply for NCVT/SCVT trade seats in government or private ITIs in Karnataka.",
                "key_action": "Submit Online ITI Counseling Form",
            },
            {
                "step_number": 2,
                "title": "Practical Workshop Apprenticeship",
                "description": "Complete intensive practical shop-floor training and National Trade Certificate (NTC) exams.",
                "key_action": "Pass NCVT All India Trade Test (AITT)",
            },
            {
                "step_number": 3,
                "title": "Industry Employment / Self-Employment",
                "description": "Join public sector utilities (KPTCL, BESCOM), manufacturing plants, or set up an independent technical workshop.",
                "key_action": "Register on NATS Apprenticeship Portal",
            },
        ],
    },

    # -------------------------------------------------------------
    # LEVEL 1: PUC STREAMS (PUC 1st Year)
    # -------------------------------------------------------------
    {
        "id": "puc-science",
        "recommendation_dimensions": ['science'],
        "education_level": "PUC 1",
        "stream": "Science",
        "title": "PUC Science Stream",
        "category": "Pre-University",
        "duration": "2 Years",
        "description": "Physics, Chemistry, and Mathematics focus combined with elective combinations. Essential prep for professional STEM fields.",
        "parent_id": "c10-puc",
        "options": [
            {
                "option_name": "PCMB (Physics, Chemistry, Mathematics, Biology)",
                "stream_or_code": "PCMB",
                "description": "Ideal for students keeping both engineering and medical/biotech pathways open.",
                "eligibility": "PUC 1st Year Science",
                "display_order": 1,
            },
            {
                "option_name": "PCMC (Physics, Chemistry, Mathematics, Computer Science)",
                "stream_or_code": "PCMC",
                "description": "Ideal for students targeting Software Engineering, Computing, AI/ML, and Pure Mathematics.",
                "eligibility": "PUC 1st Year Science",
                "display_order": 2,
            },
            {
                "option_name": "PCME (Physics, Chemistry, Mathematics, Electronics)",
                "stream_or_code": "PCME",
                "description": "Ideal for students targeting hardware engineering, robotics, and VLSI systems.",
                "eligibility": "PUC 1st Year Science",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "First PUC Board Exams",
                "description": "Secure foundational concepts in PCMX combinations.",
                "key_action": "Clear 1st PUC district/board assessment",
            },
            {
                "step_number": 2,
                "title": "Entrance Coaching Intake",
                "description": "Begin formal mocks for KCET, COMEDK, or NEET-UG.",
                "key_action": "Perform mock tests weekly",
            },
        ],
    },
    {
        "id": "puc-commerce",
        "recommendation_dimensions": ['commerce'],
        "education_level": "PUC 1",
        "stream": "Commerce",
        "title": "PUC Commerce Stream",
        "category": "Pre-University",
        "duration": "2 Years",
        "description": "Business, Accountancy, and Economics core. Sets foundations for corporate finance, corporate law, and business analytics.",
        "parent_id": "c10-puc",
        "options": [
            {
                "option_name": "CEBA (Computer Science, Economics, Business, Accountancy)",
                "stream_or_code": "CEBA",
                "description": "Mixes financial structures with computer applications and database systems.",
                "eligibility": "PUC 1st Year Commerce",
                "display_order": 1,
            },
            {
                "option_name": "SEBA (Statistics, Economics, Business, Accountancy)",
                "stream_or_code": "SEBA",
                "description": "Focuses on quantitative analytics, economics, and business accountancy.",
                "eligibility": "PUC 1st Year Commerce",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Accounting Basics",
                "description": "Master double-entry bookkeeping, ledger entries, and final accounts.",
                "key_action": "Complete core Accounting coursework",
            },
        ],
    },
    {
        "id": "puc-arts",
        "recommendation_dimensions": ['arts'],
        "education_level": "PUC 1",
        "stream": "Arts",
        "title": "PUC Arts & Humanities",
        "category": "Pre-University",
        "duration": "2 Years",
        "description": "Social sciences, languages, and human systems. Prepares students for public policy, law, journalism, and public services.",
        "parent_id": "c10-puc",
        "options": [
            {
                "option_name": "HEPS (History, Economics, Political Science, Sociology)",
                "stream_or_code": "HEPS",
                "description": "Classic combination for Civil Services (UPSC / KPSC) and Social Science majors.",
                "eligibility": "PUC 1st Year Arts",
                "display_order": 1,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Critical Reading & Analysis",
                "description": "Develop skills in essay writing, political theory, and historical analysis.",
                "key_action": "Participate in debates & writing seminars",
            },
        ],
    },

    # -------------------------------------------------------------
    # LEVEL 2: PUC SUBJECT COMBINATIONS (PUC 2nd Year)
    # -------------------------------------------------------------
    {
        "id": "puc-science-pcmb",
        "recommendation_dimensions": ['science'],
        "education_level": "PUC 2",
        "stream": "Science",
        "title": "PUC Science PCMB Pathways",
        "category": "Pre-University",
        "duration": "1 Year",
        "description": "Physics, Chemistry, Mathematics, Biology. Leads to Medical (NEET), Pharmacy, Agricultural Sciences, Engineering (KCET), or Pure Sciences.",
        "parent_id": "puc-science",
        "options": [
            {
                "option_name": "Medicine & Health Sciences (MBBS, BDS, BAMS)",
                "stream_or_code": "MED-HLTH",
                "description": "Regulated clinical medical practice programs requiring NEET-UG qualification.",
                "eligibility": "Min 50% in PCB in 2nd PUC",
                "display_order": 1,
            },
            {
                "option_name": "Pharmacy Degrees (B.Pharm / D.Pharm)",
                "stream_or_code": "PHARM",
                "description": "Pharmaceutical chemistry, clinical practice, and industrial manufacturing routes.",
                "eligibility": "2nd PUC PCMB/PCMC Pass",
                "display_order": 2,
            },
            {
                "option_name": "Agriculture & Allied Sciences",
                "stream_or_code": "AGRI",
                "description": "Horticulture, forestry, and agricultural biotechnology degrees in state agri universities.",
                "eligibility": "2nd PUC PCMB Pass (Agri quota eligible)",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "2nd PUC Board Exam",
                "description": "Pass board exams with high scores to qualify for admissions criteria.",
                "key_action": "Secure 50%+ aggregate in PCB/M",
            },
            {
                "step_number": 2,
                "title": "Competitive Exam Registration",
                "description": "Submit applications for NEET-UG and KCET.",
                "key_action": "Submit applications before deadline",
            },
        ],
    },
    {
        "id": "puc-science-pcmc",
        "recommendation_dimensions": ['science'],
        "education_level": "PUC 2",
        "stream": "Science",
        "title": "PUC Science PCMC Pathways",
        "category": "Pre-University",
        "duration": "1 Year",
        "description": "Physics, Chemistry, Mathematics, Computer Science. Leads to Engineering (B.E/B.Tech), Architecture (NATA), Computer Applications, or Pure Sciences.",
        "parent_id": "puc-science",
        "options": [
            {
                "option_name": "Engineering & Technology (B.E / B.Tech)",
                "stream_or_code": "ENG-TECH",
                "description": "Professional engineering degree in computer science, software, communications, mechanics, or infrastructure.",
                "eligibility": "Min 45% in PCM in 2nd PUC",
                "display_order": 1,
            },
            {
                "option_name": "Architecture (B.Arch)",
                "stream_or_code": "ARCH",
                "description": "5-year professional program in spatial planning, structural modeling, and design.",
                "eligibility": "2nd PUC Math Pass + NATA score",
                "display_order": 2,
            },
            {
                "option_name": "Computer Applications & IT (BCA / B.Sc CS)",
                "stream_or_code": "COMP-IT",
                "description": "Undergraduate degree in algorithms, software tools, and digital solutions.",
                "eligibility": "2nd PUC Pass (Math background preferred)",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "2nd PUC Science Boards",
                "description": "Score highly in Mathematics, Physics, and Computer Science.",
                "key_action": "Obtain official 2nd PUC Marks Card",
            },
            {
                "step_number": 2,
                "title": "KEA KCET / COMEDK Exams",
                "description": "Appear for state counseling entrance exams.",
                "key_action": "Complete counseling registration via KEA portal",
            },
        ],
    },
    {
        "id": "puc-science-pcme",
        "recommendation_dimensions": ['science'],
        "education_level": "PUC 2",
        "stream": "Science",
        "title": "PUC Science PCME Pathways",
        "category": "Pre-University",
        "duration": "1 Year",
        "description": "Physics, Chemistry, Mathematics, Electronics. Leads to Engineering, Electronics hardware, robotics, or Pure Sciences.",
        "parent_id": "puc-science",
        "options": [
            {
                "option_name": "Electronics & Electrical Engineering (B.E ECE/EEE)",
                "stream_or_code": "ENG-ELEC",
                "description": "Focuses on semiconductor chips, VLSI design, communication circuits, and power grids.",
                "eligibility": "Min 45% in PCM in 2nd PUC",
                "display_order": 1,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "2nd PUC Boards",
                "description": "Score qualification marks in board examinations.",
                "key_action": "Obtain official marks card",
            },
        ],
    },
    {
        "id": "puc-commerce-fin",
        "recommendation_dimensions": ['commerce'],
        "education_level": "PUC 2",
        "stream": "Commerce",
        "title": "PUC Commerce Finance Pathways",
        "category": "Pre-University",
        "duration": "1 Year",
        "description": "Accountancy, Economics, Business, and Statistics/Comp Science. Leads to CA, CS, B.Com, BBA, and finance careers.",
        "parent_id": "puc-commerce",
        "options": [
            {
                "option_name": "Bachelor of Commerce (B.Com / B.Com Honours)",
                "stream_or_code": "BCOM",
                "description": "Foundations in financial accounting, auditing, banking, taxation, and corporate laws.",
                "eligibility": "2nd PUC Commerce Pass",
                "display_order": 1,
            },
            {
                "option_name": "Bachelor of Business Administration (BBA)",
                "stream_or_code": "BBA",
                "description": "Principles of management, marketing, human resource development, and corporate strategy.",
                "eligibility": "2nd PUC Pass (Any stream)",
                "display_order": 2,
            },
            {
                "option_name": "Chartered Accountancy (CA) / CS / CMA Professional Track",
                "stream_or_code": "CA-TRACK",
                "description": "Direct professional qualifications under ICAI, ICSI, and ICMAI. Must be pursued alongside or after degrees.",
                "eligibility": "Pass CA Foundation Exam after 2nd PUC",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "2nd PUC Commerce Boards",
                "description": "Score qualifying marks in Accountancy, Business Studies, and Economics.",
                "key_action": "Pass board exams with 50%+",
            },
            {
                "step_number": 2,
                "title": "CA Foundation Registration",
                "description": "Enroll in the ICAI portal for the CA entry-level exam.",
                "key_action": "Submit registration form on ICAI portal",
            },
        ],
    },
    {
        "id": "puc-arts-hum",
        "recommendation_dimensions": ['arts'],
        "education_level": "PUC 2",
        "stream": "Arts",
        "title": "PUC Arts Humanities Pathways",
        "category": "Pre-University",
        "duration": "1 Year",
        "description": "History, Economics, Political Science, and Sociology. Leads to B.A., Journalism, Design, Social Work, and public sector careers.",
        "parent_id": "puc-arts",
        "options": [
            {
                "option_name": "Bachelor of Arts (B.A. in Economics/History/Pol Sci)",
                "stream_or_code": "BA",
                "description": "Core degree options in social sciences, ideal for civil service aspirants.",
                "eligibility": "2nd PUC Pass",
                "display_order": 1,
            },
            {
                "option_name": "Journalism & Mass Communication",
                "stream_or_code": "JOURNALISM",
                "description": "Print, digital media, video production, public relations, and broadcasting careers.",
                "eligibility": "2nd PUC Pass",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "2nd PUC Arts Board Exams",
                "description": "Obtain qualifications in humanities topics.",
                "key_action": "Complete final PUC exams",
            },
        ],
    },

    # -------------------------------------------------------------
    # LEVEL 3: HIGHER EDUCATION DEGREES (Undergraduate Level)
    # -------------------------------------------------------------
    {
        "id": "puc-science-eng",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Engineering & Technology (B.E / B.Tech)",
        "category": "Higher Education",
        "duration": "4 Years",
        "description": "4-year professional engineering degree program under VTU or autonomous colleges. Direct path to tech development, analytics, design, and manufacture.",
        "parent_id": "puc-science-pcmc",
        "options": [
            {
                "option_name": "Computer Science & Engineering (CSE / AI & ML / Data Science)",
                "stream_or_code": "B.E-CSE",
                "description": "Software architecture, coding, algorithms, cloud systems, and data intelligence.",
                "eligibility": "KEA KCET / COMEDK allotment",
                "display_order": 1,
            },
            {
                "option_name": "Electronics & Communication Engineering (ECE / Embedded / VLSI)",
                "stream_or_code": "B.E-ECE",
                "description": "Microcontrollers, semiconductors, IoT networks, digital circuits, and signal processing.",
                "eligibility": "KEA KCET / COMEDK allotment",
                "display_order": 2,
            },
            {
                "option_name": "Mechanical Engineering / Robotics & Automation",
                "stream_or_code": "B.E-MECH",
                "description": "CAD design, automation systems, aerospace, thermal power, and manufacturing.",
                "eligibility": "KEA KCET / COMEDK allotment",
                "display_order": 3,
            },
            {
                "option_name": "Civil Engineering & Infrastructure",
                "stream_or_code": "B.E-CIVIL",
                "description": "Structural engineering, transportation planning, smart city systems, and environment.",
                "eligibility": "KEA KCET / COMEDK allotment",
                "display_order": 4,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "KCET Seat Allotment",
                "description": "Complete online document verification and seat choice entry on KEA portal.",
                "key_action": "Secure official admission order",
            },
            {
                "step_number": 2,
                "title": "Practical Lab & Projects",
                "description": "Participate in campus labs, build project portfolios, and clear semester exams.",
                "key_action": "Maintain CGPA above 7.0",
            },
            {
                "step_number": 3,
                "title": "Capstone Project & Internships",
                "description": "Complete final-year technical project and industry training.",
                "key_action": "Build Git portfolio and complete internship",
            },
        ],
    },
    {
        "id": "puc-science-med",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Medicine & Health Sciences",
        "category": "Higher Education",
        "duration": "4.5 - 5.5 Years",
        "description": "Integrated clinical degree programs for medical practice, dentistry, alternative therapy, or healthcare operations.",
        "parent_id": "puc-science-pcmb",
        "options": [
            {
                "option_name": "MBBS / BDS Clinical Professional",
                "stream_or_code": "MBBS-BDS",
                "description": "Allopathic medicine and surgery or dental surgery degrees under Rajiv Gandhi University of Health Sciences (RGUHS).",
                "eligibility": "NEET-UG counseling allocation",
                "display_order": 1,
            },
            {
                "option_name": "BAMS / BHMS Ayurveda & Homeopathy",
                "stream_or_code": "AYURVEDA",
                "description": "Alternative medical practices, clinical diagnosis, and health wellness systems.",
                "eligibility": "NEET-UG qualified",
                "display_order": 2,
            },
            {
                "option_name": "Nursing / Physiotherapy / Allied Health Sciences",
                "stream_or_code": "ALLIED-HLTH",
                "description": "Critical clinical support systems: diagnostics, physiotherapy, or nursing.",
                "eligibility": "2nd PUC PCMB Pass (Entrance or merit)",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "NEET-UG Counseling Merit",
                "description": "Obtain necessary rank in national counseling processes.",
                "key_action": "Secure medical seat allocation",
            },
            {
                "step_number": 2,
                "title": "Rotatory Clinical Internship",
                "description": "Complete 1-year compulsory internship in a recognized hospital.",
                "key_action": "Obtain Clinical Registration License",
            },
        ],
    },
    {
        "id": "puc-science-pure",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Pure & Applied Sciences (B.Sc)",
        "category": "Higher Education",
        "duration": "3 - 4 Years",
        "description": "Basic sciences, mathematics, statistics, or biotechnology degree programs. Path to research, analytics, and industrial laboratory roles.",
        "parent_id": "puc-science-pcmb",
        "options": [
            {
                "option_name": "B.Sc (Physics / Math / Computer Science / Statistics)",
                "stream_or_code": "BSC-PURE",
                "description": "Fundamental quantitative sciences, analytical logic, and data analysis.",
                "eligibility": "2nd PUC Science Pass",
                "display_order": 1,
            },
            {
                "option_name": "B.Sc (Biotechnology / Microbiology / Biochemistry)",
                "stream_or_code": "BSC-LIFE",
                "description": "Biological processes, laboratory tech, genetics, and pharmaceutical research.",
                "eligibility": "2nd PUC Biology Pass",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Undergraduate Research Project",
                "description": "Conduct project research in target scientific disciplines.",
                "key_action": "Publish or submit final thesis",
            },
        ],
    },
    {
        "id": "puc-science-pharm",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Pharmacy Education (B.Pharm / D.Pharm)",
        "category": "Higher Education",
        "duration": "2 - 4 Years",
        "description": "Study of pharmaceutical formulations, chemistry, clinical trials, and drug business management.",
        "parent_id": "puc-science-pcmb",
        "options": [
            {
                "option_name": "Bachelor of Pharmacy (B.Pharm)",
                "stream_or_code": "B-PHARM",
                "description": "4-year professional program in pharmaceutical manufacture, quality, and clinical studies.",
                "eligibility": "2nd PUC PCMB/PCMC Pass + KCET Pharmacy ranking",
                "display_order": 1,
            },
            {
                "option_name": "Diploma in Pharmacy (D.Pharm)",
                "stream_or_code": "D-PHARM",
                "description": "2-year practical diploma in pharmacy operations, compounding, and retail regulations.",
                "eligibility": "2nd PUC Pass (PCB/PCM)",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Registered Pharmacist License",
                "description": "Register with the State Pharmacy Council after course completion.",
                "key_action": "Obtain Pharmacy License certificate",
            },
        ],
    },
    {
        "id": "puc-science-agri",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Agriculture & Allied Sciences",
        "category": "Higher Education",
        "duration": "4 Years",
        "description": "Degree programs under UAS Bengaluru, Dharwad, Raichur or Shivamogga. Covers crop management, food tech, and agri engineering.",
        "parent_id": "puc-science-pcmb",
        "options": [
            {
                "option_name": "B.Sc (Honours) Agriculture / Horticulture / Forestry",
                "stream_or_code": "BSC-AGRI",
                "description": "Modern agricultural technologies, organic production, crop protection, and forest resources.",
                "eligibility": "KEA KCET Agri Counseling allocation",
                "display_order": 1,
            },
            {
                "option_name": "B.Tech Agricultural Engineering / Food Technology",
                "stream_or_code": "BTECH-AGRI",
                "description": "Irrigation design, food processing machinery, storage technology, and packaging systems.",
                "eligibility": "KCET Engineering / Agri rank",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Rural Agricultural Work Experience (RAWE)",
                "description": "Live in a village community to understand local agricultural problems first-hand.",
                "key_action": "Complete RAWE project presentation",
            },
        ],
    },
    {
        "id": "puc-science-comp",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Computer Applications & IT",
        "category": "Higher Education",
        "duration": "3 Years",
        "description": "Practical computer systems, coding languages, web design, and database administration.",
        "parent_id": "puc-science-pcmc",
        "options": [
            {
                "option_name": "BCA (Bachelor of Computer Applications)",
                "stream_or_code": "BCA",
                "description": "Applied computing, database management, cloud systems, and software interface coding.",
                "eligibility": "2nd PUC Pass (Math/CS background preferred)",
                "display_order": 1,
            },
            {
                "option_name": "B.Sc Computer Science / B.Sc IT",
                "stream_or_code": "BSC-CS",
                "description": "Academic computer science, programming design, and basic network administration.",
                "eligibility": "2nd PUC Science Pass",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Software Project Portfolio",
                "description": "Develop full-stack web or mobile applications to show employers.",
                "key_action": "Upload coding project to GitHub",
            },
        ],
    },
    {
        "id": "puc-science-arch",
        "recommendation_dimensions": ['science'],
        "education_level": "Undergraduate",
        "stream": "Science",
        "title": "Architecture & Spatial Planning",
        "category": "Higher Education",
        "duration": "5 Years",
        "description": "5-year professional B.Arch degree under COA regulations. Focuses on structural designing, layout plans, and landscape architecture.",
        "parent_id": "puc-science-pcmc",
        "options": [
            {
                "option_name": "B.Arch (Bachelor of Architecture)",
                "stream_or_code": "B-ARCH",
                "description": "Core architecture, planning, structural designing, CAD modelling, and urban history.",
                "eligibility": "2nd PUC Pass + NATA qualifying rank",
                "display_order": 1,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "NATA Architecture Entrance",
                "description": "Appear for National Aptitude Test in Architecture (NATA).",
                "key_action": "Obtain minimum NATA cut-off score",
            },
            {
                "step_number": 2,
                "title": "6-Month Architectural Internship",
                "description": "Work in an approved architectural firm to gain practical blueprint drafting experience.",
                "key_action": "Obtain internship completion certificate",
            },
        ],
    },

    # -------------------------------------------------------------
    # MULTI-STREAM & CROSS-STREAM DEGREES (Science, Commerce, Arts)
    # -------------------------------------------------------------
    {
        "id": "cross-law",
        "recommendation_dimensions": ['commerce', 'arts', 'science'],
        "education_level": "Undergraduate",
        "stream": None,
        "title": "Integrated Law Programs (5-Year)",
        "category": "Higher Education",
        "duration": "5 Years",
        "description": "Integrated double degree law programs under Karnataka State Law University (KSLU) or National Law School (NLSIU). Bar Council eligibility.",
        "parent_id": "c10-puc",
        "options": [
            {
                "option_name": "BA LL.B (Integrated Bachelor of Arts & Law)",
                "stream_or_code": "BA-LLB",
                "description": "Ideal for Arts and Science students. Political science, history, sociology, and core legal studies.",
                "eligibility": "2nd PUC Pass (Min 45% aggregate)",
                "display_order": 1,
            },
            {
                "option_name": "BBA LL.B / B.Com LL.B (Integrated Biz/Comm & Law)",
                "stream_or_code": "BBA-BCOM-LLB",
                "description": "Ideal for Commerce students. Business strategy, corporate accounting, corporate law, and trade regulations.",
                "eligibility": "2nd PUC Pass (Commerce background preferred)",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "CLAT / LSAT Law Entrance",
                "description": "Appear for Common Law Admission Test for NLUs or local law entrances.",
                "key_action": "Secure qualifying rank for counseling",
            },
            {
                "step_number": 2,
                "title": "Moot Court & Legal Drafts",
                "description": "Complete mock court proceedings, legal drafting drills, and internships.",
                "key_action": "Participate in national level moot court rounds",
            },
            {
                "step_number": 3,
                "title": "State Bar Council Enrollment",
                "description": "Enroll under Bar Council of Karnataka (BCK) and take the AIBE examination.",
                "key_action": "Pass All India Bar Examination",
            },
        ],
    },
    {
        "id": "cross-design",
        "recommendation_dimensions": ['arts', 'science'],
        "education_level": "Undergraduate",
        "stream": None,
        "title": "Design & Creative Programs",
        "category": "Higher Education",
        "duration": "4 Years",
        "description": "Skill-intensive creative design programs covering interface design, graphic media, animations, or product design.",
        "parent_id": "c10-puc",
        "options": [
            {
                "option_name": "Product Design / UI & UX Design",
                "stream_or_code": "UI-UX",
                "description": "Software prototypes, user interaction models, website interfaces, and physical product models.",
                "eligibility": "2nd PUC Pass (Any stream)",
                "display_order": 1,
            },
            {
                "option_name": "Communication / Graphic Design / Animation",
                "stream_or_code": "CREATIVE",
                "description": "Advertising designs, publication layouts, illustration, 3D character animation, and film media.",
                "eligibility": "2nd PUC Pass (Any stream)",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Design Aptitude Test (DAT)",
                "description": "Clear entrance tests for creative institutes (UCEED, NID, NIFT).",
                "key_action": "Obtain qualification rank",
            },
            {
                "step_number": 2,
                "title": "Creative Design Portfolio",
                "description": "Assemble a visual compilation of creative artwork, mockups, and illustrations.",
                "key_action": "Compile portfolio on Behance or personal site",
            },
        ],
    },
    {
        "id": "cross-hospitality",
        "recommendation_dimensions": ['commerce', 'arts'],
        "education_level": "Undergraduate",
        "stream": None,
        "title": "Hospitality & Tourism Management",
        "category": "Higher Education",
        "duration": "3 - 4 Years",
        "description": "Global hospitality operations, hotel administration, culinary operations, travel coordination, and event management.",
        "parent_id": "c10-puc",
        "options": [
            {
                "option_name": "Bachelor of Hotel Management (BHM)",
                "stream_or_code": "BHM",
                "description": "4-year intensive training in hotel front office, food operations, house management, and hospitality business.",
                "eligibility": "2nd PUC Pass in any stream",
                "display_order": 1,
            },
            {
                "option_name": "B.Sc Hospitality & Travel Tourism",
                "stream_or_code": "TOURISM",
                "description": "Travel logistics, hospitality customer service, resort administration, and tour event operations.",
                "eligibility": "2nd PUC Pass in any stream",
                "display_order": 2,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "6-Month Star Hotel Training",
                "description": "Complete compulsory practical operations internship in an approved 5-star hotel.",
                "key_action": "Obtain hospitality internship certificate",
            },
        ],
    },

    # -------------------------------------------------------------
    # LEVEL 4: POST-UNDERGRADUATE / CAREER DIRECTIONS (Outcomes)
    # -------------------------------------------------------------
    {
        "id": "puc-science-cse-careers",
        "recommendation_dimensions": ['science'],
        "education_level": "Career",
        "stream": "Science",
        "title": "Computing & Software Careers",
        "category": "Career Direction",
        "duration": "Continuous",
        "description": "Opportunities in technical development, cloud architecture, system safety, data pipeline setup, or AI modeling.",
        "parent_id": "puc-science-eng",
        "options": [
            {
                "option_name": "Software Development / Software Engineering",
                "stream_or_code": "SWE",
                "description": "Web, mobile, desktop backend, frontends, algorithms, and application databases.",
                "eligibility": "B.E/B.Tech CSE/ISE or BCA/MCA degree",
                "display_order": 1,
            },
            {
                "option_name": "AI Engineer / Machine Learning Engineer / Data Scientist",
                "stream_or_code": "AI-ML",
                "description": "Train predictive models, computer vision systems, NLP APIs, and large data structures.",
                "eligibility": "Math background + programming proficiency",
                "display_order": 2,
            },
            {
                "option_name": "Cybersecurity & Cloud Systems Engineer",
                "stream_or_code": "SEC-CLOUD",
                "description": "Secure virtual configurations, deploy AWS/GCP servers, configure network firewalls.",
                "eligibility": "Degree + security certifications",
                "display_order": 3,
            },
        ],
        "milestones": [
            {
                "step_number": 1,
                "title": "Technical Interviews",
                "description": "Pass data structures and algorithms evaluations.",
                "key_action": "Complete technical hiring assessments",
            },
        ],
    },
]
