use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - bing
general:
  debug: false
  instance_name: Udaan local search
search:
  safe_search: 2
  formats:
    - json
    - html
server:
  secret_key: udaan-local-internal-search-no-public-session
  limiter: false
  image_proxy: false
outgoing:
  request_timeout: 2.5
  max_request_timeout: 4.0
engines:
  - name: duckduckgo
    disabled: false
  - name: bing
    disabled: false

